from alembic import command
from factories import make_event, make_photo, unit
from sqlalchemy import delete, func, select, text

from foco.modules.events.models import Event
from foco.modules.photos.models import Face, Photo


def test_extensao_e_tabelas(session):
    tables = set(session.scalars(text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")))
    assert {"events", "photos", "faces", "feature_flags"} <= tables
    assert session.scalar(text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")) == 1


def test_modelos_batem_com_as_migracoes(engine, alembic_cfg):
    # Levanta AutogenerateDiffsDetected se um modelo mudou sem migração.
    command.check(alembic_cfg)


def test_id_de_evento_nunca_e_reusado(session):
    a = make_event(session, "A")
    session.execute(delete(Event).where(Event.id == a.id))
    b = make_event(session, "B")
    assert b.id > a.id


def test_excluir_evento_apaga_fotos_e_rostos(session):
    ev = make_event(session)
    make_photo(session, ev, faces=[((0, 0, 10, 10), unit(0), 0.9)])
    session.execute(delete(Event).where(Event.id == ev.id))
    assert session.scalar(select(func.count()).select_from(Photo)) == 0
    assert session.scalar(select(func.count()).select_from(Face)) == 0


def test_schema_do_procrastinate(session):
    assert session.scalar(text("SELECT to_regclass('procrastinate_jobs')")) is not None
