/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Features */
        get: operations["list_features_api_admin_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/features/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Feature */
        put: operations["set_feature_api_admin_features__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_admin_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session State */
        get: operations["session_state_api_admin_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        /** Create Event */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        /** Delete Event */
        delete: operations["delete_event_api_events__event_id__delete"];
        options?: never;
        head?: never;
        /** Update Event */
        patch: operations["update_event_api_events__event_id__patch"];
        trace?: never;
    };
    "/api/events/{event_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Photos */
        get: operations["list_photos_api_events__event_id__photos_get"];
        put?: never;
        /** Upload Photos */
        post: operations["upload_photos_api_events__event_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progress
         * @description Server-Sent Events: empurra o status das fotos até todas terminarem.
         *
         *     SSE é só uma resposta HTTP que nunca fecha, onde o servidor escreve
         *     linhas "data: ...\n\n". O navegador lê com `new EventSource(url)`.
         *     O status vive no Postgres (o worker é outro processo), então cada volta
         *     abre uma sessão curta e lê o banco.
         */
        get: operations["progress_api_events__event_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Features
         * @description Público: o frontend decide o que mostrar (a API bloqueia por conta própria).
         */
        get: operations["get_features_api_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo Full */
        get: operations["photo_full_api_photos__photo_id__full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/medium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo Medium */
        get: operations["photo_medium_api_photos__photo_id__medium_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo Thumb */
        get: operations["photo_thumb_api_photos__photo_id__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Busca as fotos de um evento que contêm o rosto da selfie (ou do query_token).
         */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Zip */
        get: operations["download_zip_api_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminSession */
        AdminSession: {
            /** Enabled */
            enabled: boolean;
            /** Logged In */
            logged_in: boolean;
        };
        /** Body_search_api_search_post */
        Body_search_api_search_post: {
            /** Event Id */
            event_id: number;
            /** Query Token */
            query_token?: string | null;
            /** Selfie */
            selfie?: string | null;
            /**
             * Threshold
             * @default 0.4
             */
            threshold: number;
        };
        /** Body_upload_photos_api_events__event_id__photos_post */
        Body_upload_photos_api_events__event_id__photos_post: {
            /** Files */
            files: string[];
        };
        /** CoverPhoto */
        CoverPhoto: {
            /** Fx */
            fx: number;
            /** Fy */
            fy: number;
            /** Id */
            id: number;
        };
        /** DebugHit */
        DebugHit: {
            /** Above */
            above: boolean;
            /** Bbox */
            bbox: number[];
            /** Face Id */
            face_id: number;
            /** Filename */
            filename: string;
            /** Height */
            height: number | null;
            /** Photo Id */
            photo_id: number;
            /** Score */
            score: number;
            /** Width */
            width: number | null;
        };
        /** DeleteOut */
        DeleteOut: {
            /** Deleted */
            deleted: number;
            /** Photos */
            photos: number;
        };
        /** EventIn */
        EventIn: {
            /** Event Date */
            event_date?: string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
        };
        /** EventOut */
        EventOut: {
            /** Event Date */
            event_date: string | null;
            /** Id */
            id: number;
            /** Location */
            location: string | null;
            /** Name */
            name: string;
        };
        /** EventSummary */
        EventSummary: {
            /** Cover */
            cover: components["schemas"]["CoverPhoto"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Date */
            event_date: string | null;
            /** Id */
            id: number;
            /** Location */
            location: string | null;
            /** N Done */
            n_done: number;
            /** N Faces */
            n_faces: number;
            /** N Pending */
            n_pending: number;
            /** N Photos */
            n_photos: number;
            /** Name */
            name: string;
        };
        /** FaceHit */
        FaceHit: {
            /** Bbox */
            bbox: number[];
            /** Face Id */
            face_id: number;
            /** Filename */
            filename: string;
            /** Height */
            height: number | null;
            /** Photo Id */
            photo_id: number;
            /** Score */
            score: number;
            /** Width */
            width: number | null;
        };
        /** FeatureIn */
        FeatureIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** FeatureInfo */
        FeatureInfo: {
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /** Height */
            height: number | null;
            /** Id */
            id: number;
            /** N Faces */
            n_faces: number;
            /** Proc Ms */
            proc_ms: number | null;
            /** Status */
            status: string;
            /** Width */
            width: number | null;
        };
        /**
         * ProgressOut
         * @description Payload de cada mensagem do SSE de progresso (não aparece no OpenAPI do
         *     SSE, mas o front importa o tipo deste schema).
         */
        ProgressOut: {
            /** Done */
            done: boolean;
            /** Items */
            items: components["schemas"]["PhotoOut"][];
            /** Queue */
            queue: number;
        };
        /**
         * SearchOut
         * @description Campos opcionais só aparecem quando fazem sentido (a rota usa
         *     response_model_exclude_unset): `selfie` na busca com selfie; tempos e
         *     top 30 só com a Calibração ligada.
         */
        SearchOut: {
            /** Debug Top */
            debug_top?: components["schemas"]["DebugHit"][] | null;
            /** Indexed Faces */
            indexed_faces: number;
            /** Matches */
            matches: components["schemas"]["FaceHit"][];
            /** Query Token */
            query_token: string;
            selfie?: components["schemas"]["SelfieInfo"] | null;
            /** Threshold */
            threshold: number;
            /** Timings From Cache */
            timings_from_cache?: boolean | null;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            } | null;
            /** Total Photos */
            total_photos: number;
        };
        /** SelfieInfo */
        SelfieInfo: {
            /** All Bboxes */
            all_bboxes: number[][];
            /** Bbox */
            bbox: number[];
            /** Det Score */
            det_score: number;
            /** Height */
            height: number;
            /** N Faces */
            n_faces: number;
            /** Warning */
            warning: string | null;
            /** Width */
            width: number;
        };
        /** SheetPhoto */
        SheetPhoto: {
            /** Error */
            error: string | null;
            /** Filename */
            filename: string;
            /** Fx */
            fx: number;
            /** Fy */
            fy: number;
            /** Height */
            height: number | null;
            /** Id */
            id: number;
            /** N Faces */
            n_faces: number;
            /** Proc Ms */
            proc_ms: number | null;
            /** Status */
            status: string;
            /** Width */
            width: number | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Avg Ms Per Photo */
            avg_ms_per_photo: number | null;
            /** Done */
            done: number;
            /** Errors */
            errors: number;
            /** Events */
            events: number;
            /** Faces */
            faces: number;
            /** Pending */
            pending: number;
            /** Photos */
            photos: number;
        };
        /**
         * UploadResult
         * @description Um item da resposta do upload: a foto salva (com `duplicate`) ou um erro
         *     ({filename, status: "error", error}). A rota usa response_model_exclude_unset.
         */
        UploadResult: {
            /** Duplicate */
            duplicate?: boolean | null;
            /** Error */
            error?: string | null;
            /** Filename */
            filename?: string | null;
            /** Height */
            height?: number | null;
            /** Id */
            id?: number | null;
            /** N Faces */
            n_faces?: number | null;
            /** Proc Ms */
            proc_ms?: number | null;
            /** Status */
            status: string;
            /** Width */
            width?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_features_api_admin_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureInfo"][];
                };
            };
        };
    };
    set_feature_api_admin_features__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_admin_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_state_api_admin_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_event_api_events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_events__event_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_api_events__event_id__photos_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetPhoto"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photos_api_events__event_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photos_api_events__event_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_events__event_id__progress_get: {
        parameters: {
            query?: {
                ids?: string;
            };
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_api_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    photo_full_api_photos__photo_id__full_get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_medium_api_photos__photo_id__medium_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_thumb_api_photos__photo_id__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_search_api_search_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: {
                event_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_zip_api_zip_get: {
        parameters: {
            query: {
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
