/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as CalibracaoRouteImport } from './routes/calibracao'
import { Route as EstudioIndexRouteImport } from './routes/estudio.index'
import { Route as EstudioEventIdRouteImport } from './routes/estudio.$eventId'
import { Route as GaleriaEventIdRouteImport } from './routes/galeria.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibracaoRoute = CalibracaoRouteImport.update({
  id: '/calibracao',
  path: '/calibracao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioIndexRoute = EstudioIndexRouteImport.update({
  id: '/estudio/',
  path: '/estudio/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioEventIdRoute = EstudioEventIdRouteImport.update({
  id: '/estudio/$eventId',
  path: '/estudio/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaEventIdRoute = GaleriaEventIdRouteImport.update({
  id: '/galeria/$eventId',
  path: '/galeria/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/calibracao': typeof CalibracaoRoute
  '/estudio/$eventId': typeof EstudioEventIdRoute
  '/galeria/$eventId': typeof GaleriaEventIdRoute
  '/estudio/': typeof EstudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/calibracao': typeof CalibracaoRoute
  '/estudio/$eventId': typeof EstudioEventIdRoute
  '/galeria/$eventId': typeof GaleriaEventIdRoute
  '/estudio': typeof EstudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/calibracao': typeof CalibracaoRoute
  '/estudio/$eventId': typeof EstudioEventIdRoute
  '/galeria/$eventId': typeof GaleriaEventIdRoute
  '/estudio/': typeof EstudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/calibracao'
    | '/estudio/$eventId'
    | '/galeria/$eventId'
    | '/estudio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/calibracao'
    | '/estudio/$eventId'
    | '/galeria/$eventId'
    | '/estudio'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/calibracao'
    | '/estudio/$eventId'
    | '/galeria/$eventId'
    | '/estudio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRoute
  CalibracaoRoute: typeof CalibracaoRoute
  EstudioEventIdRoute: typeof EstudioEventIdRoute
  GaleriaEventIdRoute: typeof GaleriaEventIdRoute
  EstudioIndexRoute: typeof EstudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibracao': {
      id: '/calibracao'
      path: '/calibracao'
      fullPath: '/calibracao'
      preLoaderRoute: typeof CalibracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio/': {
      id: '/estudio/'
      path: '/estudio'
      fullPath: '/estudio/'
      preLoaderRoute: typeof EstudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio/$eventId': {
      id: '/estudio/$eventId'
      path: '/estudio/$eventId'
      fullPath: '/estudio/$eventId'
      preLoaderRoute: typeof EstudioEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$eventId': {
      id: '/galeria/$eventId'
      path: '/galeria/$eventId'
      fullPath: '/galeria/$eventId'
      preLoaderRoute: typeof GaleriaEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRoute,
  CalibracaoRoute: CalibracaoRoute,
  EstudioEventIdRoute: EstudioEventIdRoute,
  GaleriaEventIdRoute: GaleriaEventIdRoute,
  EstudioIndexRoute: EstudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
